version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "reddit_posts:1:1"
    depends_on:
      - zookeeper
    container_name: kafka

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=reddit_cluster
    volumes:
      - ./cassandra/init.cql:/init.cql
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    container_name: cassandra

  cassandra-init:
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./cassandra/init.cql:/init.cql
    command: /bin/bash -c "sleep 60 && cqlsh cassandra -f /init.cql"
    container_name: cassandra-init

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    container_name: spark-master

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    container_name: spark-worker

  reddit-producer:
    build: ./producer
    depends_on:
      - kafka
    env_file:
      - .env
    container_name: reddit-producer

  sentiment-consumer:
    build: ./consumer
    depends_on:
      - kafka
      - cassandra
      - cassandra-init
      - spark-master
    container_name: sentiment-consumer

  streamlit-dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - cassandra
      - cassandra-init
    container_name: streamlit-dashboard

volumes:
  cassandra_data: